import json
import os
import subprocess
from pathlib import Path


PY_PATH = "/opt/venv310/bin/python"
OBJECT_MANIFEST = "/kaggle/working/object_images_manifest.json"


def run_grounded_sam2(input_image_path: str, layout: dict, crops_dir: str) -> list:
    """Use SAM2 on the isolated object images generated by the object-wise stage."""
    del input_image_path, layout
    if not os.path.isfile(OBJECT_MANIFEST):
        raise FileNotFoundError("Object images are missing. Run the SD3.5 object-wise stage first.")

    Path(crops_dir).mkdir(parents=True, exist_ok=True)
    script_path = "/kaggle/working/run_objectwise_sam2.py"
    script = r'''
import json
import os
import sys
sys.path.insert(0, "/opt/venv310/lib/python3.10/site-packages")
sys.modules["triton"] = None

import numpy as np
import scipy.ndimage as ndimage
from PIL import Image, ImageOps
from sam2.build_sam import build_sam2
from sam2.sam2_image_predictor import SAM2ImagePredictor

MANIFEST = "__MANIFEST__"
CROPS_DIR = "__CROPS_DIR__"
SAM2_CKPT = "/kaggle/working/sam2_ckpt/sam2_hiera_small.pt"

with open(MANIFEST, encoding="utf-8") as file:
    objects = json.load(file)

predictor = SAM2ImagePredictor(build_sam2("sam2_hiera_s.yaml", SAM2_CKPT, device="cuda"))
results = []
previews = []
for item in objects:
    image = Image.open(item["image_path"]).convert("RGB")
    rgb = np.asarray(image)
    height, width = rgb.shape[:2]
    predictor.set_image(rgb)

    margin = max(18, int(min(width, height) * 0.04))
    box = np.array([margin, margin, width - margin, height - margin], dtype=np.float32)
    masks, scores, _ = predictor.predict(box=box, multimask_output=True)
    best = int(np.argmax(scores))
    mask = ndimage.binary_closing(masks[best].astype(bool), structure=np.ones((3, 3)))
    mask = ndimage.binary_fill_holes(mask)
    alpha = ndimage.gaussian_filter(mask.astype(np.float32) * 255.0, sigma=1.0)
    alpha = np.clip(alpha, 0, 255).astype(np.uint8)

    rgba = image.convert("RGBA")
    rgba.putalpha(Image.fromarray(alpha))
    name = item["name"]
    crop_path = os.path.join(CROPS_DIR, f"{name}.png")
    rgba.save(crop_path)
    previews.append(Image.alpha_composite(Image.new("RGBA", rgba.size, "white"), rgba).convert("RGB"))
    results.append({
        "name": name,
        "label": item["label"],
        "confidence": 1.0,
        "mask_score": float(scores[best]),
        "box": [margin, margin, width - margin, height - margin],
        "final_box": [0, 0, width, height],
        "crop_path": crop_path,
        "source_mode": "objectwise_sam2",
    })

if previews:
    cards = [ImageOps.contain(image, (360, 360), Image.Resampling.LANCZOS) for image in previews]
    sheet = Image.new("RGB", (360 * min(2, len(cards)), 360 * ((len(cards) + 1) // 2)), "white")
    for index, card in enumerate(cards):
        sheet.paste(card, ((index % 2) * 360, (index // 2) * 360))
    sheet.save(os.path.join(CROPS_DIR, "sam2_visual.png"))

with open(os.path.join(CROPS_DIR, "sam2_results.json"), "w", encoding="utf-8") as file:
    json.dump(results, file, ensure_ascii=False, indent=2)
print(json.dumps(results))
'''
    script = script.replace("__MANIFEST__", OBJECT_MANIFEST).replace("__CROPS_DIR__", crops_dir)
    Path(script_path).write_text(script, encoding="utf-8")
    result = subprocess.run([PY_PATH, script_path], capture_output=True, text=True, timeout=360)
    if result.returncode != 0:
        raise RuntimeError("Object-wise SAM2 failed:\n" + result.stderr + "\n" + result.stdout)

    with open(os.path.join(crops_dir, "sam2_results.json"), encoding="utf-8") as file:
        return json.load(file)
